### ISSUE TITLE
Install script fails for Mac using versioning

### ISSUE THREAD

**Issue by JJJJJones** [bacongobbler/helm-whatup#11]
To a naive user (or API!) the latest version is 0.1.0, so helm installs using a [deprecated install-binary.sh](https://github.com/bacongobbler/helm-whatup/blob/v0.1.0/install-binary.sh#L32) which causes problems for Macs as seen in #3 (releases are searched for a non-existent helm-whatup-0.1.0-macos-amd64.tar.gz). The master branch doesn't have this problem with [install-binary.sh](https://github.com/bacongobbler/helm-whatup/blame/master/install-binary.sh#L32), correctly looking for [helm-whatup-0.1.0-darwin-amd64.tar.gz](https://github.com/bacongobbler/helm-whatup/releases/download/v0.1.0/helm-whatup-0.1.0-darwin-amd64.tar.gz).

Please make a new tag for the latest master.

**Comment by bacongobbler** [comment]
v0.2.0 has been released. Sorry for the delay.
